spring:
  application:
    name: minIO Storage
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadminpassword
  bucket: my-bucket

